[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[[redirects]]
  from = "/war-room"
  to = "/war-room.html"
  status = 301

[[redirects]]
  from = "/news"
  to = "/news.html"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

# Environment variables for API configuration
[build.environment]
  API_BASE_URL = "https://api.retaketech.com"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
